[project]
name = "ai-core-tools"
version = "0.2.17"
description = "Mattin AI by LKS Next is a tool to aid and complement other software projects with AI capabilities."
authors = [
    {name = "Aritz Galdos, Mikel Lonbide"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "flask (>=3.1.0,<4.0.0)",
    "flask-restful (>=0.3.10,<0.4.0)",
    "flask-session (>=0.8.0,<0.9.0)",
    "flask-login (>=0.6.3,<0.7.0)",
    "flask-sqlalchemy (>=3.1.1,<4.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "psycopg (>=3.2.4,<4.0.0)",
    "langchain-openai (>=0.3.2,<0.4.0)",
    "langchain (>=0.3.16,<0.4.0)",
    "pdf2image (>=1.17.0,<2.0.0)",
    "pypdf (>=5.2.0,<6.0.0)",
    "langchain-anthropic (>=0.3.4,<0.4.0)",
    "langchain-community (>=0.3.15,<0.4.0)",
    "langchain-postgres (>=0.0.12,<0.0.13)",
    "authlib (>=1.4.0,<2.0.0)",
    "deprecation (>=2.1.0,<3.0.0)",
    "flask-openapi3 (>=4.0.3,<5.0.0)",
    "langchain-mistralai (>=0.2.6,<0.3.0)",
    "mistralai (>=1.5.0,<2.0.0)",
    "flask-paginate (>=2024.4.12,<2025.0.0)",
    "beautifulsoup4 (>=4.13.3,<5.0.0)",
    "langchain-ollama (>=0.2.3,<0.3.0)",
    "langchain-mcp-adapters (>=0.0.8,<0.0.9)",
    "toml (>=0.10.2,<0.11.0)",
    "langgraph (>=0.4.10,<0.5.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
